In [2]:
import numpy as np
import pandas as pd

**Data cleaning**

In [9]:
#  importing the dataset with changing the data type of date column 
#  in to Timestamp by using parse_dates parameter and making it the index

df=pd.read_csv("train.csv",parse_dates=["date"],index_col="date")
df.head()

             id    city       lat      long  ...  container capacity price quantity
date                                         ...
2012-01-31  0.0  Athens  37.97945  23.71622  ...      glass    500ml  0.96  13280.0
2012-01-31  1.0  Athens  37.97945  23.71622  ...    plastic    1.5lt  2.86   6727.0
2012-01-31  2.0  Athens  37.97945  23.71622  ...        can    330ml  0.87   9848.0
2012-01-31  3.0  Athens  37.97945  23.71622  ...      glass    500ml  1.00  20050.0
2012-01-31  4.0  Athens  37.97945  23.71622  ...        can    330ml  0.39  25696.0

[5 rows x 11 columns]

In [8]:
type(df.date[0])

pandas._libs.tslibs.timestamps.Timestamp

In [11]:
#dropping the id column sinceit does not contribute to the target variable quantity.

df.drop(["id"],axis=1)

              city       lat      long  ...  capacity price quantity
date                                    ...
2012-01-31  Athens  37.97945  23.71622  ...     500ml  0.96  13280.0
2012-01-31  Athens  37.97945  23.71622  ...     1.5lt  2.86   6727.0
2012-01-31  Athens  37.97945  23.71622  ...     330ml  0.87   9848.0
2012-01-31  Athens  37.97945  23.71622  ...     500ml  1.00  20050.0
2012-01-31  Athens  37.97945  23.71622  ...     330ml  0.39  25696.0
...            ...       ...       ...  ...       ...   ...      ...
NaT            NaN       NaN       NaN  ...       NaN   NaN      NaN
NaT            NaN       NaN       NaN  ...       NaN   NaN      NaN
NaT            NaN       NaN       NaN  ...       NaN   NaN      NaN
NaT            NaN       NaN       NaN  ...       NaN   NaN      NaN
NaT            NaN       NaN       NaN  ...       NaN   NaN      NaN

[7560 rows x 10 columns]

In [13]:
df.dropna(axis=0)

                id          city       lat  ...  capacity  price quantity
date                                        ...
2012-01-31     0.0        Athens  37.97945  ...     500ml   0.96  13280.0
2012-01-31     1.0        Athens  37.97945  ...     1.5lt   2.86   6727.0
2012-01-31     2.0        Athens  37.97945  ...     330ml   0.87   9848.0
2012-01-31     3.0        Athens  37.97945  ...     500ml   1.00  20050.0
2012-01-31     4.0        Athens  37.97945  ...     330ml   0.39  25696.0
...            ...           ...       ...  ...       ...    ...      ...
2017-12-31  6475.0        Athens  37.96245  ...     1.5lt   1.02  33201.0
2017-12-31  6476.0        Larisa  39.63689  ...     330ml   0.47  46971.0
2017-12-31  6477.0         Patra  38.24444  ...     500ml   1.02  47708.0
2017-12-31  6478.0  Thessaloniki  40.64361  ...     1.5lt   1.34  27115.0
2017-12-31  6479.0  Thessaloniki  40.64361  ...     500ml   1.16  30413.0

[6376 rows x 11 columns]

In [14]:
df
#when we see the data there are some values missing, but the adjacent
# values are same in ao we use fillna methode and ffill parameter to carry backward the value in the next cell to the previous.

             id    city       lat      long  ...  container capacity price quantity
date                                         ...
2012-01-31  0.0  Athens  37.97945  23.71622  ...      glass    500ml  0.96  13280.0
2012-01-31  1.0  Athens  37.97945  23.71622  ...    plastic    1.5lt  2.86   6727.0
2012-01-31  2.0  Athens  37.97945  23.71622  ...        can    330ml  0.87   9848.0
2012-01-31  3.0  Athens  37.97945  23.71622  ...      glass    500ml  1.00  20050.0
2012-01-31  4.0  Athens  37.97945  23.71622  ...        can    330ml  0.39  25696.0
...         ...     ...       ...       ...  ...        ...      ...   ...      ...
NaT         NaN     NaN       NaN       NaN  ...        NaN      NaN   NaN      NaN
NaT         NaN     NaN       NaN       NaN  ...        NaN      NaN   NaN      NaN
NaT         NaN     NaN       NaN       NaN  ...        NaN      NaN   NaN      NaN
NaT         NaN     NaN       NaN       NaN  ...        NaN      NaN   NaN      NaN
NaT         NaN     NaN       NaN       NaN  ...        NaN      NaN   NaN      NaN

[7560 rows x 11 columns]

In [17]:
df.fillna(method="bfill",inplace=True)

In [18]:
df.dropna(inplace=True)
# the rows from index 6480 are all empty , we just have to drop them
#so we use dropna methode

In [19]:
df

                id          city       lat  ...  capacity  price quantity
date                                        ...
2012-01-31     0.0        Athens  37.97945  ...     500ml   0.96  13280.0
2012-01-31     1.0        Athens  37.97945  ...     1.5lt   2.86   6727.0
2012-01-31     2.0        Athens  37.97945  ...     330ml   0.87   9848.0
2012-01-31     3.0        Athens  37.97945  ...     500ml   1.00  20050.0
2012-01-31     4.0        Athens  37.97945  ...     330ml   0.39  25696.0
...            ...           ...       ...  ...       ...    ...      ...
2017-12-31  6475.0        Athens  37.96245  ...     1.5lt   1.02  33201.0
2017-12-31  6476.0        Larisa  39.63689  ...     330ml   0.47  46971.0
2017-12-31  6477.0         Patra  38.24444  ...     500ml   1.02  47708.0
2017-12-31  6478.0  Thessaloniki  40.64361  ...     1.5lt   1.34  27115.0
2017-12-31  6479.0  Thessaloniki  40.64361  ...     500ml   1.16  30413.0

[6480 rows x 11 columns]

**Using Label encoder to convert object colums to numbers**

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le_city = LabelEncoder().  #CREATING OBJECTS FOR EACH OBJECT COLUMN.
le_shop = LabelEncoder()
le_brand = LabelEncoder()
le_container =LabelEncoder()
le_capacity = LabelEncoder()

In [30]:
df["city_n"]=le_city.fit_transform(df['city']) #creating a new column city_n and labeling it ising label encoder 
df["shop_n"]=le_shop.fit_transform(df['shop']) #doing the same for the rest
df["brand_n"]=le_brand.fit_transform(df['brand'])
df["container_n"]=le_container.fit_transform(df['container'])
df["capacity_n"]=le_capacity.fit_transform(df['capacity'])

In [31]:
df.head()

             id    city       lat  ...  brand_n  container_n capacity_n
date                               ...
2012-01-31  0.0  Athens  37.97945  ...        2            1          2
2012-01-31  1.0  Athens  37.97945  ...        2            2          0
2012-01-31  2.0  Athens  37.97945  ...        2            0          1
2012-01-31  3.0  Athens  37.97945  ...        0            1          2
2012-01-31  4.0  Athens  37.97945  ...        0            0          1

[5 rows x 16 columns]

In [34]:
df_new = df.drop(["city",'shop','brand','container','capacity'],axis=1)

In [39]:
df_new.drop(["id"],axis=1,inplace=True)

In [40]:
df_new

                 lat      long       pop  ...  brand_n  container_n  capacity_n
date                                      ...
2012-01-31  37.97945  23.71622  672130.0  ...        2            1           2
2012-01-31  37.97945  23.71622  672130.0  ...        2            2           0
2012-01-31  37.97945  23.71622  672130.0  ...        2            0           1
2012-01-31  37.97945  23.71622  672130.0  ...        0            1           2
2012-01-31  37.97945  23.71622  672130.0  ...        0            0           1
...              ...       ...       ...  ...      ...          ...         ...
2017-12-31  37.96245  23.68708  665871.0  ...        4            2           0
2017-12-31  39.63689  22.41761  144302.0  ...        4            0           1
2017-12-31  38.24444  21.73444  168501.0  ...        0            1           2
2017-12-31  40.64361  22.93086  353001.0  ...        1            2           0
2017-12-31  40.64361  22.93086  353001.0  ...        0            1           2

[6480 rows x 10 columns]

In [41]:
from sklearn.model_selection import TimeSeriesSplit

n_splits = 3 #Number of train/cv/test folds

trainTestSplit = TimeSeriesSplit(n_splits+1).split(df_new)
next(trainTestSplit) #Skip the first fold

for trainCvIndices, testIndices in trainTestSplit:
    # First, we split Train + CV and Test
    XTrainCv, yTrainCv = df_new.iloc[trainCvIndices,0], df_new.iloc[trainCvIndices,1]
    XTest, yTest       = df_new.iloc[testIndices,0]   , df_new.iloc[testIndices,1]
    
    # Then, we build a list of the form [ ( [...Train Indices...], [...CV Indices...]  )]
    testLength = len(XTest)
    trainCvSplit = [(list(range(trainCvIndices[0],trainCvIndices[-testLength])),
                     list(range(trainCvIndices[-testLength],trainCvIndices[-1]+1)))]
    
    # Printing date ranges
    print("Training:"           , XTrainCv.index[0].date(), "--", XTrainCv.index[-testLength-1].date(),
          ", Cv:"     , XTrainCv.index[-testLength].date(), "--", XTrainCv.index[-1].date(),
          ", Test:"                , XTest.index[0].date(), "--", XTest.index[-1].date())

Training: 2012-01-31 -- 2013-03-31 , Cv: 2013-03-31 -- 2014-05-31 , Test: 2014-05-31 -- 2015-08-31
Training: 2012-01-31 -- 2014-05-31 , Cv: 2014-05-31 -- 2015-08-31 , Test: 2015-08-31 -- 2016-10-31
Training: 2012-01-31 -- 2015-08-31 , Cv: 2015-08-31 -- 2016-10-31 , Test: 2016-10-31 -- 2017-12-31

In [42]:
from sklearn.linear_model import LassoCV

modelCV = LassoCV().fit(XTrainCv,yTrainCv)

ValueError: ignored